site_name: SNEL11 Docs
repo_url: https://github.com/robesistemasuser/snel11-docs
edit_uri: edit/main/docs/
nav:
  - Inicio: index.md
  - Arquitectura:
    - Visión general: architecture/overview.md
    - Módulos: architecture/modules.md
    - Plantillas de módulos: architecture/modules-templates.md
    - Permisos (SubmoduleAccess): architecture/permissions.md
    - Actions (patrón): architecture/actions.md
    - ERD + Secuencias Inventarios: architecture/inventories-erd-sequences.md
  - Módulos:
    - Inventarios / Categorías (Importación): modules/inventories/categories-import.md
  - Compras:
    - Estados de OC: purchases/oc-states.md
    - Clases y permisos: purchases/classes-permissions.md
  - Operaciones:
    - Entorno local: operations/local-setup.md
    - Despliegue: operations/deploy.md
    - Troubleshooting: operations/troubleshooting.md
  - Generados:
    - Rutas: _generated/routes.md
    - Modelos: _generated/models.md
    - Livewire: _generated/livewire-components.md
    - Migraciones: _generated/migrations.md
theme:
  name: material
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
